### ISSUE TITLE
Parse new deprecation notices to internal contract via REST

### ISSUE THREAD

**Issue by tomkerkhove** [azure-deprecation/infrastructure#4]
We should provide an API which allows us to post a new deprecation notice which translates it into our internal contract and gives it back to the consumer.

The API should provide OpenAPI specs with documentation and contract information about request/response.

## Input
```markdown
Azure Automation Service Management REST APIs are being retired.

**Deadline:** April 30, 2019
**Impacted Services:** Azure Automation
**More information:** https://azure.microsoft.com/en-us/updates/azure-automation-service-management-rest-apis-are-being-retired-april-30-2019/

### Notice

> Azure Service Management (ASM) REST APIs for Azure Automation will be retired and no longer supported after April 30, 2019. Azure Resource Manager, our next-generation cloud infrastructure stack, fully replaces these APIs and provides many additional benefits, including:
> -  Increased security with role-based access control (RBAC)
> - Support for resource grouping and tags
> - A streamlined deployment and management process 

### Impact

> If you’re unsure whether you’re using Service Management REST APIs, check the URI referenced in your code or service. If it’s https://management.core.windows.net, you’re using Service Management REST APIs and you should migrate to Resource Manager REST APIs.
> 
> If you’re unsure whether you’re using Service Management PowerShell cmdlets, check whether the cmdlet name includes AzureRM (for example, Get-AzureRmAutomationAccount) or Az (for example, Get-AzAutomationAccount). If it doesn’t include AzureRM or Az (for example, Get-AzureAutomationAccount), you should migrate to Resource Manager PowerShell cmdlets.

### Required Action
> Migrate any Azure Automation Service Management REST APIs and PowerShell cmdlets for Azure Automation to Resource Manager REST APIs or the latest PowerShell cmdlets by April 30, 2019, to take advantage of advanced capabilities and avoid any service disruptions.
```

**Labels:**
`impact:action-required`, `services:automation`

### Notes
- `Impacted Services` can be a comma separated list
- Every service will have a corresponding label a la `services:{name}`, however, we should ignore this as this is just to allow people to filter issues by service
- We use labels to indicate the impact of the deprecation and should be included in the internal contract.
   - Options are: `impact:action-required`, `impact:limited`, `impact:none`, `impact:unknown`

## Expected Output Proposal
```json
{
    "notice": {
        "title": "Azure Automation Service Management REST APIs are being retired",
        "deprecationDate": "2019-04-30T00:00:00Z",
        "announcementUrl": "https://azure.microsoft.com/en-us/updates/azure-automation-service-management-rest-apis-are-being-retired-april-30-2019/",
        "impact": {
            "action": "none|required|limited",
            "services": [
                "Azure Automation"
            ]
        }
    },
    "github": {
        "issueId": "2",
        "state": "open",
        "reportedBy": "TomKerkhove",
        "createdAt": "2019-04-19T13:16:55Z",
        "updatedAt": "2019-04-19T13:16:55Z",
        "repoUrl": "https://github.com/azure-deprecation/dashboard"
    }
}
```

**Comment by tomkerkhove** [comment]
FYI @SeanFeldman

**Comment by SeanFeldman** [comment]
Expected output, the `notice.impact.action` field has an issue.

Currently it says `"action": "none|required|limited"`, but that's not matching any of the proposed options (`impact:action-required`, `impact:limited`, `impact:none`, `impact:unknown`). Did you mean for it to be  `"action": "action-required"` based on the given input?

Clarification: action can be more than one action multiple labels `impact:???` are applied?

And last, but not the least - how do you want the code to be implemented? Right now repo skeleton is empty.

**Comment by tomkerkhove** [comment]
We fully control the labels so it's up to use, I figured the proposed contract made more sense but maybe I'm wrong but it should only have one label.

The code should be easily deployable, operable and managed. Consumers will call it via REST.
I think the options are Azure Functions or Azure Container Instances and am leaning towards ACI given it's a Docker container which I can verify easily test & deploy.

What are your suggestions?

**Comment by SeanFeldman** [comment]
If you want it as an ACI or Function, need to know which one to pick. ACI means it's just an .NET Core assembly. If it's a Function, need to cater to use Functions SDK. I'll let you choose which one to use 🙂

**Comment by tomkerkhove** [comment]
Let's follow your suggestion and go with Functions, I'll give it another shot ;)
