### ISSUE TITLE
Migrate to .NET 6.x & Azure Functions v4.x

### ISSUE THREAD

**Issue by tomkerkhove** [azure-deprecation/infrastructure#66]
Migrate to .NET 6.x since 3.1 is going to be deprecated.

**Comment by tomkerkhove** [comment]
This impacts migration from Azure Functions v3 to v4: https://learn.microsoft.com/en-us/azure/azure-functions/functions-versions?tabs=azure-cli%2Cin-process%2Cv4&pivots=programming-language-csharp#migrating-from-3x-to-4x

**Comment by dechev** [comment]
Include central nuget version management in Directory.Packages.props
